### PR TITLE
Support new multiplatform model (1.2.70+, including 1.3.0+)

### PR DESCRIPTION
**Pull request by snrostov**
- Only one JS target is supported for now
- Example similar to project created by wizard (JS client, JVM server)
- Update to gradle 4.8 and kotlin 1.3.10

### CODE REVIEW

**Comment by snrostov** [comment]
Fixes #117

**Comment by wem** [comment]
Similar problem. JsMainApi and JsMainImplementation configuration (test configuration i thing too) dependencies are not added to package.json. Therefore, i get build failures like:

```
ERROR` in ./shared-common.js
Module not found: Error: Can't resolve 'kotlinx-serialization-runtime-js' in '/home/michel/project/scape-system/shared/shared-common/build/js'
 @ ./shared-common.js 970:37-80
```

**Comment by snrostov** [comment]
@wem Can you please share your project? It is working in PR's example and test: `kotlin` and `kotlin-test` dependencies are added to `build/package.json`.

**Comment by wem** [comment]
[project.zip](https://github.com/Kotlin/kotlin-frontend-plugin/files/2660074/project.zip)

I just started to migrate. You can use the Gradle project under shared/shared-common. That's the project i tested.

**Comment by wem** [comment]
Damn :) ... i forgot the compile task names. Thx!

**Pull request merged**
