### PR TITLE
Update to Kotlin 1.3.10 and Gradle 5.0

### LINKED ISSUE #124: Gradle 5.0  error NpmPackageManager$injectDependencies$1$1 does not define or inherit a method
This plugin fails hard under Gradle 5.0

> * What went wrong:
> Receiver class org.jetbrains.kotlin.gradle.frontend.npm.NpmPackageManager$injectDependencies$1$1 does not define or inherit an implementation of the resolved method getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; of interface org.gradle.api.file.FileCollection.

### PR DESCRIPTION
**Pull request by kapot65**
Fix deprecated code
- fix #124

### CODE REVIEW

**Comment by talon** [comment]
I'm eager to see this merged as it is the only thing blocking multiplatform builds for me, is there anyway I can help? @kapot65

**Comment by coder82** [comment]
Urgent :=)

**Comment by JakeWharton** [comment]
@kapot65 can you rebase this so it's mergeable again?

**Comment by snrostov** [comment]
@kapot65 Things in `Package.install` should be executed only in Idea Gradle project import/sync. I fixed and merged it into master manually: 6a869729 and 6f69279d. 

Will be released soon.

**Pull request closed without merging**
