### PR TITLE
Support for passing options in devServer.

### LINKED ISSUE #34: devServer.historyApiFallback
https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback

I'd like to set this option on my devServer. Adding a new `webpack.config.d` file with this does not work.

```
config.devServer = {
    historyApiFallback: true
};
```

### PR DESCRIPTION
**Pull request by vkhikhlov**
This Closes #34

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Doesn't it require additional npm dependency? We probably need to add it automatically if there is corresponding config so user don't need to worry about it

**Comment by vkhikhlov** [comment]
No, It's just one of the webpack-dev-server dependencies.

**Comment by vkhikhlov** [comment]
But, I've only just read in webpack documentation:

> If you're using dev-server through the Node.js API, the options in devServer will be ignored. Pass the options as a second parameter instead: new WebpackDevServer(compiler, {...}).

So, I think it'd be better to rewrite it another way, in order to allow customization of all devserver options.

**Comment by cy6erGn0m** [comment]
Thanks!

**Comment by darren-bell-nanthealth** [comment]
Is there a description/documentation of how i can set historyApiFallback? I'm sorry but its not clear to me. 
Thanks

**Comment by darren-bell-nanthealth** [comment]
Figured it out, created a file in the webpack.config.d folder with 

config.devServer = {
    historyApiFallback: true,
}

in it

**Pull request merged**
