### PR TITLE
Added support for yarn

### PR DESCRIPTION
**Pull request by jesse-bonzo**
To take advantage of yarn's caching:

```
npm {
    dependency("react")
}
```

can become

```
yarn {
    dependency("react")
}
```

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Yarn should be implemented as a separate PackageMenager implementation. Now it's completely mixed with npm.

**Comment by jesse-bonzo** [comment]
Please take another look when you have a chance

**Comment by jonninja** [comment]
Any chance this could move forward? The npm situation is killer, as `clean build` requires us to completely pull new npm modules from a remote server.

**Comment by cy6erGn0m** [comment]
This version looks much better. I'd like to see at least a smoke test. Look for `testNpmOnly`. You could add similar for yarn

**Comment by jesse-bonzo** [comment]
I've pushed the latest code I had, but I don't think it's working anymore.
When time permits I will try and get a working version pushed.

**Comment by chadmorrow-fd** [comment]
I think that last commit got everything working. Anyone able to take a look and see if it can be merged?

**Comment by cy6erGn0m** [comment]
Ok, going to review and merge manually

**Comment by cy6erGn0m** [comment]
@jesse-bonzo Does yarn support symlinks in node_modules? It is REQUIRED to be able to extract non-npm packages (unpacked from maven repo). npm install simply ignores symlinks so it works perfect however yarn fails if there is no such package in npm.

**Comment by chadmorrow-fd** [comment]
This is the extent of yarn's support for symlinks: https://yarnpkg.com/en/docs/cli/link

**Comment by cy6erGn0m** [comment]
It creates a relative symlink (that is dangerous). Also I am still getting `error An unexpected error occurred: "https://registry.yarnpkg.com/kotlinx-io-js: Not found".` in spite of that there is a link

**Comment by jonninja** [comment]
The current situation is pretty bad, because every time we perform a `clean` we have to re-get everything remotely. Some kind of solution for that is necessary for this plugin.

**Pull request closed without merging**
